### ISSUE TITLE
Pass input as command line arguments

### ISSUE THREAD

**Issue by iglpdc** [hookerlab/petmr-database-tools#1]
It'd be better if the scripts take the input as an argument in the command line, instead just going by default in the interactive mode. This way we could chain the three scripts in a larger one.

If the script is passed with no arguments, then it falls back to the current interactive mode.

We could use [docopt](http://docopt.org/): it's awesome for this kind of thing.

**Comment by iglpdc** [comment]
Hi @strike127, do you wanna implement this? For example, for the merging script, I'd like to be able to do:

```
python jsonMerge.py path/to/radiopharm.json path/to/dose_info.json
```

In case I just do `python  jsonMerge.py` I should get the current version.

**Comment by strike127** [comment]
Sure I can do that. 
So it would be allowing the user to just enter the paths without the 'enter path to....' prompt correct?
ie
python RpLog.py path/to/radiopharm.csv
python doseInfoOneJSONFile.py path/to/starting directory/to/find/dose_info.xls
python jsonMerge.py path/to/radiopharm.json path/to/dose_info.json

or did you want it to be
python jsonMerge.py path/to/radiopharm.json path/to/dose_info.json
and jsonMerge.py would call the other two files and have their 'enter path to ...' prompt

**Comment by iglpdc** [comment]
> python RpLog.py path/to/radiopharm.csv
> python doseInfoOneJSONFile.py path/to/starting directory/to/find/dose_info.xls
> python jsonMerge.py path/to/radiopharm.json path/to/dose_info.json

I think this is better. We can later decide how to put them all together.
