### ISSUE TITLE
Match the PET files with their Bourget subject IDs

### ISSUE THREAD

**Issue by iglpdc** [hookerlab/petmr-database-tools#2]
All the PET files have the same name and are stored in a central location in some server somewhere (we don't have access to this yet.)

We need a script that crawls down from a given directory and find all the PET files. Their name is 'Frame1.lst', although some subjects have more than one PET file. In this case, the files are named 'Frame2.lst', 'Frame3.lst', etc.... We could reuse the crawler function from the dose info script. 

This script takes one argument: the starting point to crawl the filesystem.

For each PET file found, the script should get the **full** path where the file is and the md5sum checksum of the file. ~~and the creation/modification date of the file. For the modification dates we can use  `os.path.getctime(path)` and `os.path.getctime(path)` (See [this SO question](http://stackoverflow.com/questions/237079/how-to-get-file-creation-modification-date-times-in-python) for the difference between the two).~~

The output of the script is a JSON object with these two pieces of data. E.g. if we have:

```
$ find /path/to/PET/files -name "Frame*.lst"
one_folder/Frame_1.lst
another_folder/Frame_1.lst
```
the script should return:

```
$ find_pet_files /path/to/PET/files
[ {"frame": "/path/to/PET/files/one_folder/Frame_1.lst",
   "md5sum": "9tlwjer8pqok0"},
 {"frame": "/path/to/PET/files/another_folder/Frame_1.lst",
   "md5sum": "lkwjeri3o4i0"}
]
```
(Or something like this).

The file path also encodes the date when the scan was taken and could be another piece of information to match the PET file with the subject id.

**Comment by iglpdc** [comment]
The structure of the folder containing all the files has subdirectories like this:

```
petcore\PET_computer_backup\Year_2012\Mar\Mar09\Patient
petcore\PET_computer_backup\Year_2012\Dec\Dec14\Patient1
petcore\PET_computer_backup\Year_2015\May\May14\Patient_C11_Gerstner_TMZ
```

The first example is for a day 2012-03-09 with just one patient scanned, so the directory holding the scan date is labelled 'Patient'. The second example is for a day with more than one patient and patients where labelled consecutively. The third example is for a day with more than one patient, but encoding some extra information in the folder name.

Inside each of the three folders there is a a folder (maybe inside another folders) containing a Dose_info.xls file and one (or more than one) PET files.

So the idea is to use the path we are getting from this script to match the Dose_info.xls with all their PET files. Then using the "series time" field from the Dose_info we can match this with the info in the radiopharm log. which has the subject id.

**Comment by iglpdc** [comment]
@strike127 take a look to what I wrote. (I'm not sure if it's clear enough, probably not...) We can discuss here as until we have clear what we want to do.

**Comment by iglpdc** [comment]
1. Yes, the name pattern for the PET files is `Frame*.lst` and the extension is always `.lst`
2. The [checksum](https://en.wikipedia.org/wiki/Checksum) is a short string that identifies the file uniquely. I want to have that for two things:
 1. if the file is ever moved, and as all have the same name, the checksum could help us to see which is the subject id for the PET file
 2. to check if the file has been corrupted (the checksum would be different from the recorded)
3. Yes, `jsonMerge.py` would be the one that merges the two files.

>1. Match Dose_info.xls files with PET files(How should it be outputted to say if a PET file is for >Dose_info.xls? Like another JSON object of PET file path, Dose_info.xls Path and the subject ID of the > patient?)

What I want to have at the very end is one JSON object per subject id. The JSON object would have all the info from the Dose info file plus the one in the radiopharm log plus which are the PET files corresponding to this subject. 

The advantages of having all in JSON format is that most tools and libraries have a function to load directly from JSON, so we don't have to write much code after this to enter the data in a SQL database or to use it in our MATLAB code.

So, yes, the final JSON thing should have "subject_id", "dose_info_path", and "frames", where "frames" is an array of paths and checksums, like the output of the `find_pet_files` above:

```
$ find_pet_files /path/to/PET/files
[ {"frame": "/path/to/PET/files/one_folder/Frame_1.lst",
   "md5sum": "9tlwjer8pqok0"},
 {"frame": "/path/to/PET/files/another_folder/Frame_1.lst",
   "md5sum": "lkwjeri3o4i0"}
]
```
Feel free to choose other names or change the output if you see I'm missing something.

**Comment by strike127** [comment]
A question about the directories for the Dose_info.xls and pet files

Are the Dose_info.xls files in the same folder as the PET files?
ie
if in: petcore\PET_computer_backup\Year_2012\Mar\Mar09\Patient
it contains both Dose_info.xls and PET files in the 'Patient' directory
so:
petcore\PET_computer_backup\Year_2012\Mar\Mar09\Patient\Dose_info.xls
petcore\PET_computer_backup\Year_2012\Mar\Mar09\Patient\Frame1.lst

or
lets say Dose_info.xls is in 'Patient' directory but in the 'Patient' directory there is also a subdirectory and the PET files are in the subdirectory  or vice versa
so:
petcore\PET_computer_backup\Year_2012\Mar\Mar09\Patient\Dose_info.xls
petcore\PET_computer_backup\Year_2012\Mar\Mar09\Patient\subfolder\Frame1.lst
vice versa would be
petcore\PET_computer_backup\Year_2012\Mar\Mar09\Patient\Frame1.lst
petcore\PET_computer_backup\Year_2012\Mar\Mar09\Patient\subfolder\Dose_info.xls

Another case: The Dose_info.xls and PET files are within a subdirectory while only the subdirectory is in the parent directory.
ie.
parent directory:  petcore\PET_computer_backup\Year_2012\Mar\Mar09\Patient
which contains: 'subdirectory'
petcore\PET_computer_backup\Year_2012\Mar\Mar09\Patient\subdirectory
which contains: Dose_info.xls and PET files
petcore\PET_computer_backup\Year_2012\Mar\Mar09\Patient\subdirectory\Dose_info.xls
petcore\PET_computer_backup\Year_2012\Mar\Mar09\Patient\subdirectory\Frame1.lst

Another question:
If there are more than 1 PET file for a patient, would they all be in the same directory?
ie
if the PET files are in: petcore\PET_computer_backup\Year_2012\Mar\Mar09\Patient
Would all PET files be in 'Patient'
petcore\PET_computer_backup\Year_2012\Mar\Mar09\Patient\Frame1.lst
petcore\PET_computer_backup\Year_2012\Mar\Mar09\Patient\Frame2.lst

or 
are there cases where some of the PET files are in a subdirectory
petcore\PET_computer_backup\Year_2012\Mar\Mar09\Patient\Frame1.lst
petcore\PET_computer_backup\Year_2012\Mar\Mar09\Patient\subdirectory\Frame2.lst

**Comment by iglpdc** [comment]
I'm not really sure. Probably there are some weird combinations of all the above. We can assume that all the PET files are in the same directory for a given patient. 

Also, most of the time the Dose info and the PET files would be in the same directory (so your first case). We can try assuming this for the first version of the script, run it with real data and see if we get by or have to change it.

**Comment by strike127** [comment]
Did you want finding the PET files as a separate script or would it be fine if I do it in doseInfoOneFIleJson.py, so we don't have to crawl through the directories a second time.

**Comment by iglpdc** [comment]
I think it's better to have an array of frame and md5sums rather than two arrays, one of frames, one of sums.

**Comment by strike127** [comment]
I'm a bit confused, what do you mean by having an array for frame and array for md5sum but not two arrays.

**Comment by iglpdc** [comment]
I think it's better to have:

```
[ {"frame": "path/to/frame1, "checksum": checksum1}, {"frame":
"path/to/frame2, "checksum": checksum2}, ...]
```

rather than


```
{"frames": ["path/to/frame1, "path/to/frame2",..], "checksums": [checksum1,
checksum2,...]}
```
