### ISSUE TITLE
merging the Json files question

### ISSUE THREAD

**Issue by strike127** [hookerlab/petmr-database-tools#4]
@iglpdc 
are the labels being compared for merging the following:

in RadioPharmLog                                       in Dose_info
Date                                            ----->         Scan Date
Scan Time/Injection Time           ----->?        Which time do I compare with radiopharm's time?(Series?)

**Comment by iglpdc** [comment]
Scan Time/Injection time in the radiopharm log are the same as Series Time and TOI in the Dose info file. Just to be sure, match Scan Time/Injection time in the radiopharm log to TOI in Dose info (cell E3).

Most of the time Series Time, Acquisition time and TOI are the same, but strictly speaking the one we have to match is TOI.
